
ALTER TABLE `WorksComplite` CHANGE `Cost` `Cost` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `WorksComplite` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Basket` CHANGE `Summ` `Summ` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Bonuses` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Contracts` CHANGE `Balance` `Balance` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsBonuses` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsConsider` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsConsider` CHANGE `Cost` `Cost` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsSchemes` CHANGE `CostOrder` `CostOrder` DECIMAL( 6, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsSchemes` CHANGE `CostProlong` `CostProlong` DECIMAL( 6, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DomainsSchemes` CHANGE `CostTransfer` `CostTransfer` DECIMAL( 6, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostDay` `CostDay` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostMonth` `CostMonth` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostInstall` `CostInstall` DECIMAL( 11, 2 ) NOT NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ExtraIPSchemes` CHANGE `CostDay` `CostDay` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ExtraIPSchemes` CHANGE `CostMonth` `CostMonth` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ExtraIPSchemes` CHANGE `CostInstall` `CostInstall` DECIMAL( 11, 2 ) NOT NULL;
-- SEPARATOR
ALTER TABLE `HostingSchemes` CHANGE `CostDay` `CostDay` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `HostingSchemes` CHANGE `CostMonth` `CostMonth` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Invoices` CHANGE `Summ` `Summ` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `InvoicesItems` CHANGE `Summ` `Summ` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ISPswSchemes` CHANGE `CostDay` `CostDay` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ISPswSchemes` CHANGE `CostMonth` `CostMonth` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `ISPswSchemes` CHANGE `CostInstall` `CostInstall` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `OrdersConsider` CHANGE `Cost` `Cost` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `OrdersConsider` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Politics` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Postings` CHANGE `Before` `Before` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Postings` CHANGE `After` `After` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `PromoCodes` CHANGE `Discont` `Discont` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Services` CHANGE `CostOn` `CostOn` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Services` CHANGE `Cost` `Cost` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Users` CHANGE `Rating` `Rating` DECIMAL( 7, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Users` CHANGE `LayPayMaxSumm` `LayPayMaxSumm` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `Users` CHANGE `LayPayThreshold` `LayPayThreshold` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSSchemes` CHANGE `CostDay` `CostDay` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSSchemes` CHANGE `CostMonth` `CostMonth` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSSchemes` CHANGE `CostInstall` `CostInstall` DECIMAL( 11, 2 ) NULL DEFAULT '0.00';

