
ALTER TABLE `ISPswLicenses` ADD `pricelist_id` INT(12) NOT NULL AFTER `ID`;
-- SEPARATOR
ALTER TABLE `ISPswLicenses` ADD `period` VARCHAR(32) NOT NULL AFTER `pricelist_id`;
-- SEPARATOR
ALTER TABLE `ISPswLicenses` ADD `addon` INT(12) NOT NULL DEFAULT '1' AFTER `period`;
-- SEPARATOR
ALTER TABLE `ISPswLicenses` DROP `ISPtype`;

-- SEPARATOR
ALTER TABLE `ISPswSchemes` ADD `pricelist_id` INT(12) NOT NULL;
-- SEPARATOR
ALTER TABLE `ISPswSchemes` ADD `period` VARCHAR(32) NOT NULL;
-- SEPARATOR
ALTER TABLE `ISPswSchemes` ADD `addon` INT(12) NOT NULL DEFAULT '1';
-- SEPARATOR
ALTER TABLE `ISPswSchemes` DROP `ISPtype`;


