
ALTER TABLE `DSSchemes` ADD `ILOpass` CHAR(64) NOT NULL DEFAULT '' AFTER `Switch`;
-- SEPARATOR
ALTER TABLE `DSSchemes` ADD `ILOuser` VARCHAR(32) NOT NULL DEFAULT '' AFTER `Switch`;
-- SEPARATOR
ALTER TABLE `DSSchemes` ADD `ILOaddr` VARCHAR(128) NOT NULL DEFAULT '' AFTER `Switch`;
-- SEPARATOR
ALTER TABLE `DSSchemes` ADD `DSpass` CHAR(64) NOT NULL DEFAULT '' AFTER `Switch`;
-- SEPARATOR
ALTER TABLE `DSSchemes` ADD `DSuser` VARCHAR(32) NOT NULL DEFAULT '' AFTER `Switch`;
-- SEPARATOR
ALTER TABLE `DSSchemes` ADD `IPaddr` VARCHAR(32) NOT NULL DEFAULT '' AFTER `Switch`;





