ALTER TABLE `VPSSchemes` CHANGE `CostDay` `CostDay` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSSchemes` CHANGE `CostMonth` `CostMonth` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostDay` `CostDay` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostMonth` `CostMonth` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSPolitics` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSDomainsPolitics` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `VPSBonuses` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSSchemes` CHANGE `CostInstall` `CostInstall` FLOAT( 11, 2 ) NOT NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSPolitics` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSDomainsPolitics` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
-- SEPARATOR
ALTER TABLE `DSBonuses` CHANGE `Discont` `Discont` FLOAT( 11, 2 ) NULL DEFAULT '0.00';
