
ALTER TABLE `ExtraIPs` DROP `IsOK`;

-- SEPARATOR

ALTER TABLE `Servers` CHANGE `IsOK` `IsOK` INT(3) NULL DEFAULT NULL;

-- SEPARATOR

ALTER TABLE `DSServers` CHANGE `IsOK` `IsOK` INT(3) NULL DEFAULT NULL;


